### ISSUE TITLE
Application unit can be stuck in the "Configuring pod" state

### ISSUE THREAD

**Issue by exceptorr** [relaxdiego/charm-k8s-prometheus#6]
![image](https://user-images.githubusercontent.com/2902448/82335757-71e21a00-99f2-11ea-9c46-85cd4779ab27.png)

I got a weird condition where config-changed was never triggered so application left in this state. I did a "juju config prom ..." and it switched to the active/idle status.

Need to investigate further.

**Comment by relaxdiego** [comment]
This should have been resolved by #3, right?

**Comment by exceptorr** [comment]
Resolved by #3
